server:
  port: 8080
spring:
  profiles:
    active: info
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/stock_data?rewriteBathedStatements=true&characterEncoding=utf8&useSSL=false
    username: ZKB
    password: 123456789
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true