server:
  port: 8080
spring:
  profiles:
    active: info
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/contract_eap?rewriteBathedStatements=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true